apiVersion: 1

datasources:
  - name: Gold Warehouse
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    isDefault: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600